version: "3.8"

services:
  # VPN
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn   
    cap_add:
     - NET_ADMIN
    volumes:
     - $DOCKER_PATH/openvpn/conf:/etc/openvpn
    ports:
     - "10194:1194/udp"     
    restart: unless-stopped
  # Transmission
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    env_file:
      - linuxserver.env
    volumes:
      - $DOCKER_PATH/transmission/config:/config
      - $TORRENT_PATH:/watch
      - $DOWNLOAD_PATH:/downloads
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped
  # Syncthing
  syncthing:
    image: ghcr.io/linuxserver/syncthing    
    container_name: syncthing
    env_file:
      - linuxserver.env
    volumes:
      - $DOCKER_PATH/syncthing/config:/config
      - $DOCKER_PATH/syncthing/data:/data
    ports:
      - "7504:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart: unless-stopped
  # Jackett
  jackett:
    image: ghcr.io/linuxserver/jackett    
    container_name: jackett
    env_file:
      - linuxserver.env
    environment:
      - AUTO_UPDATE=true
    volumes:
      - $DOCKER_PATH/jackett:/config
      - $TORRENT_PATH:/downloads
    ports:
      - "7506:9117"
    restart: unless-stopped       
  # Cron job - Backups
  cron:
    image: registry.local.lpda.se/cron:latest
    container_name: cron    
    env_file:
      - egna.env
      - .secrets  
    volumes:
      - $DOCKER_PATH:/data/
      - $DATA_PATH/backup/:/backup/
    restart: unless-stopped          
  # PeterPedia - Collection of my own apps.
  peterpedia:
    image: ghcr.io/peter-andersson/peterpedia:latest
    container_name: peterpedia
    env_file:
      - egna.env
      - .secrets
    environment:
      - ConnectionStrings__PeterPedia=Data Source=/db/peterpedia.db
    volumes:
        - /volume1/docker/peterpedia/db/:/db
        - /volume1/docker/peterpedia/logs:/logs
        - /volume1/data/videos:/video
        - /volume1/data/photos:/photos
        - /volume1/docker/peterpedia/images:/images
    ports:
      - "7202:80/tcp"        
    restart: unless-stopped            
